### ISSUE TITLE
Remove use of isort

### ISSUE THREAD

**Issue by saroad2** [Zac-HD/shed#2]
# Why should you remove *isort*?
At the moment, *isort* depends on the virtual environment it runs on. It means that running *isort* on different machines causes different sorting for the imports. This is especially important in CI/CD processes.

This is a bug that will be fixed only on version 5.0.0 of *isort*, so until then I suggest removing the usage of *isort* here.

## A little side-note.

I started to develop my own tool that does exactly what you do here!
It is called [Eddington-static](https://github.com/EddLabs/eddington-static) and it runs *Black*, *flake8*, *mypy*, *pylint* and *pydocstyle*.
It also configurable using *commands.toml* file, so you can add/remove/edit commands as much as you want.
Maybe we can consider joining forces and make a single tool ;)

**Comment by Zac-HD** [comment]
Hey @saroad2 - thanks for commenting!

You're exactly right about `isort`, and that's one of the two reasons that `shed` is currently "pre-alpha" software - I'm waiting for the release of Isort 5 (ETA... several months ago) which will fix this.  You can see my comments here:

https://github.com/Zac-HD/shed/blob/c859d2babc8846e5ce0666b941832bc7178aa585/src/shed/__init__.py#L65-L70

(the other reason is that I currently use some pyupgrade internals, which are subject to breaking changes without notice.  Fine if you pin versions, but many people don't...)

---------

Eddington-static looks cool!  I think we have a difference of opinion though - with `shed` I'm aiming to build a tool which *cannot be configured*, and *never requires the user to take action*.

It fixes everything it can, and anything it can't automatically fix is out of scope.  This philosophy makes tools *incredibly* easy to use - or decide not to use - because there is only one decision to make: are we using this or not?

**Comment by saroad2** [comment]
Just to clarify: *Eddington-static* **do not require configuration too**. It has a default configuration that most people would use without even knowing it (Think about *Black*. when was the last time you added a flag to a *Black* run?).

The difference is that you **can** configure it if you want to, and I think this is an important thing. most people won't need to ever configuration it, but if they wanted - they could.

Good luck man! If you change your mind, let me know.

**Comment by Zac-HD** [comment]
> most people won't need to ever configuration it, but if they wanted - they could.

Not for `shed` - if you want to configure it, use a differnt tool.  Makes documentation and debugging very simple... of course this isn't for everyone, but there are plenty of other tools out there.
