### ISSUE TITLE
Internal errors when running on pytest with `--refactor`

### ISSUE THREAD

**Issue by The-Compiler** [Zac-HD/shed#35]
With shed 0.9.5 and Python 3.10.4, running `shed --refactor` over pytest, I get:

```
Internal error formatting 'doc/en/example/pythoncollection.rst': SyntaxError: multiple exception types must be parenthesized (<unknown>, line 5)
    Please report this to https://github.com/Zac-HD/shed/issues
Internal error formatting 'doc/en/how-to/writing_plugins.rst': SyntaxError: positional argument follows keyword argument (<unknown>, line 1)
    Please report this to https://github.com/Zac-HD/shed/issues
```

**Comment by Zac-HD** [comment]
This is genuinely invalid syntax in the pytest docs' example code, but you're correct that `shed` should handle that better.

**Comment by glnnlhmn** [comment]
Investigated this issue during mentored sprints at PyCon 2022.  Reproduced the error by placing a syntax error in writing_plugins.rst and running shed over the file.  

The invalid code block invoked pytest import handling in a way that created an error. 

Spoke with Zac and determined the issue is not worth handling, and the current behavior is acceptable.

**Comment by Zac-HD** [comment]
Thanks Glenn - this was surprisingly gnarly to track down, so I'm glad we got to the bottom of it 😃
