### ISSUE TITLE
Dependencies installation failed

### ISSUE THREAD

**Issue by Cheukting** [Zac-HD/shed#6]
Somehow tox failed to install com2ann for 3.8 and dataclasses for black for python 3.7. Have you seen the same problem? The problematic builds are here: https://travis-ci.com/github/terminusdb/terminusdb-client-python/builds/182622894

**Comment by Zac-HD** [comment]
Yes, I've seen similar issues before - because the dependencies vary by Python version, you'll need to pin the dependencies per-version too.  See https://github.com/jazzband/pip-tools/pull/651 for details.

(this is incidentally my one wish for `pip-compile`; if it propogated environment markers instead of resolving them)
